services:
  aqi-app:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    container_name: aqi-dashboard
    ports:
      - "8080:8080"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always
    depends_on:
      - aqi-app
